vim.g.mapleader =
" "                           -- Set global leader key to space (also defined in keymaps.lua)
vim.opt.number = true         -- Enable line numbers
vim.opt.relativenumber = true -- Make line numbers relative
vim.opt.termguicolors = true  -- Enable all colors supported ny nvim
vim.opt.laststatus = 1        -- Size of status line
vim.opt.mouse = "a"           -- Enable mouse mode
vim.opt.cursorline = true     -- Enable highlighting of the current line
vim.opt.autochdir = true      -- Automatically change directory
vim.opt.ignorecase = true     -- Ignore case
vim.opt.smartcase = true      -- Don't ignore case with capitals
vim.wo.wrap = false           -- Set no wrap
vim.wo.linebreak = false      -- Set no linebreak
vim.wo.list = false           -- Set no list >
vim.opt.tabstop = 2           -- Tab set to 4 instead of 8
vim.opt.shiftwidth = 2        -- Tab set to 4 instead of 8
vim.opt.background = "dark"   -- Or "light" for light mode
vim.opt.foldlevelstart = 99
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
-- vim.opt.foldcolumn = "1"
